'use strict';
/**
 * ============================================================
 * fabricService.js — UPDATED with Broadcast Encryption support
 * Blockchain E-Health Access Control System
 * ============================================================
 *
 * CHANGES FROM PREVIOUS VERSION:
 *   storeHash()        → accepts broadcastHeader as 6th argument
 *   revokeAccess()     → NEW: removes user from broadcast header
 *   addAuthorizedUser()→ NEW: adds user to broadcast header
 *
 * Replace: app/services/fabricService.js
 * ============================================================
 */

const { Gateway, Wallets } = require('fabric-network');
const path = require('path');
const fs = require('fs');
const broadcastService = require('./broadcastService');

// Path to the connection profile generated by fabric-samples
const ccpPath = path.resolve(
    process.env.HOME,
    'fabric-samples', 'test-network', 'organizations',
    'peerOrganizations', 'org1.example.com',
    'connection-org1.json'
);

// Path to the wallet holding enrolled identities
const walletPath = path.join(process.cwd(), 'wallet');

// ─────────────────────────────────────────────────────────────
// getContract — internal helper
// Opens Gateway → Channel → Contract
// Always call gateway.disconnect() in finally block
// ─────────────────────────────────────────────────────────────
async function getContract() {
    if (!fs.existsSync(ccpPath)) {
        throw new Error(
            `Connection profile not found at ${ccpPath}.\n` +
            `Run: cd ~/fabric-samples/test-network/organizations && ./ccp-generate.sh`
        );
    }

    const ccp = JSON.parse(fs.readFileSync(ccpPath, 'utf8'));
    const wallet = await Wallets.newFileSystemWallet(walletPath);

    const identity = await wallet.get('appUser');
    if (!identity) {
        throw new Error(
            'appUser identity not found in wallet.\n' +
            'Run: cd app && node enrollAdmin.js'
        );
    }

    const gateway = new Gateway();
    await gateway.connect(ccp, {
        wallet,
        identity: 'appUser',
        discovery: { enabled: true, asLocalhost: true }
    });

    const network = await gateway.getNetwork('healthchannel');
    const contract = network.getContract('healthcontract');

    return { contract, gateway };
}

// ─────────────────────────────────────────────────────────────
// registerUser — Algorithm 1: register a user on blockchain
// ─────────────────────────────────────────────────────────────
async function registerUser(userId, publicKey, role) {
    const { contract, gateway } = await getContract();
    try {
        const result = await contract.submitTransaction(
            'UserRegistry:registerUser',
            userId, publicKey, role
        );
        return JSON.parse(result.toString());
    } finally {
        gateway.disconnect();
    }
}

// ─────────────────────────────────────────────────────────────
// assignLevel — Algorithm 3: assign L0–L3 privacy level
// ─────────────────────────────────────────────────────────────
async function assignLevel(userId, level) {
    const { contract, gateway } = await getContract();
    try {
        const result = await contract.submitTransaction(
            'PrivacyLevel:assignLevel',
            userId, level
        );
        return JSON.parse(result.toString());
    } finally {
        gateway.disconnect();
    }
}

// ─────────────────────────────────────────────────────────────
// storeHash — UPDATED: now accepts broadcastHeader
// Stores IPFS hash + IV + privacy level + broadcast header on chain
// ─────────────────────────────────────────────────────────────
async function storeHash(dataId, patientId, ipfsHash, iv, level, broadcastHeader = '{}') {
    const { contract, gateway } = await getContract();
    try {
        const result = await contract.submitTransaction(
            'DataStorage:storeHash',
            dataId,
            patientId,
            ipfsHash,
            iv,
            level,
            broadcastHeader || '{}'    // ← ensure never undefined
        );
        return JSON.parse(result.toString());
    } finally {
        gateway.disconnect();
    }
}

// ─────────────────────────────────────────────────────────────
// requestAccess — Algorithm 5: check access and return encrypted key
// Response now includes encryptedKeyForYou if GRANTED
// ─────────────────────────────────────────────────────────────
async function requestAccess(requesterId, dataId) {
    const { contract, gateway } = await getContract();
    try {
        const result = await contract.submitTransaction(
            'DataAccess:requestAccess',
            requesterId,
            dataId
        );
        return JSON.parse(result.toString());
    } finally {
        gateway.disconnect();
    }
}

// ─────────────────────────────────────────────────────────────
// revokeAccess — NEW: remove a user from broadcast header
// Does NOT re-encrypt the file (that's the whole point)
// ─────────────────────────────────────────────────────────────
async function revokeAccess(dataId, revokedUserId) {
    const { contract, gateway } = await getContract();
    try {
        // Step 1: Get current data record to read existing header
        const dataResult = await contract.evaluateTransaction(
            'DataStorage:getDataRecord',
            dataId
        );
        const dataRecord = JSON.parse(dataResult.toString());

        // Step 2: Remove user from header using broadcastService
        const updatedHeader = broadcastService.revokeUserFromHeader(
            dataRecord.broadcastHeader || {},
            revokedUserId
        );

        // Step 3: Write updated header back to blockchain
        const result = await contract.submitTransaction(
            'DataStorage:updateBroadcastHeader',
            dataId,
            JSON.stringify(updatedHeader),
            `revoke:${revokedUserId}`
        );

        return JSON.parse(result.toString());
    } finally {
        gateway.disconnect();
    }
}

// ─────────────────────────────────────────────────────────────
// addAuthorizedUser — NEW: add a user to existing broadcast header
// Requires: the AES key K must be provided (by patient who knows it)
// In production: patient decrypts their own entry to get K, then re-encrypts for new user
//
// NOTE: For simplicity here, the patient must provide aesKeyHex
//       In a fully client-side implementation, this would happen in the browser
// ─────────────────────────────────────────────────────────────
async function addAuthorizedUser(dataId, newUserId, newUserPublicKey, aesKeyHex) {
    const { contract, gateway } = await getContract();
    try {
        // Step 1: Get current data record
        const dataResult = await contract.evaluateTransaction(
            'DataStorage:getDataRecord',
            dataId
        );
        const dataRecord = JSON.parse(dataResult.toString());

        // Step 2: Add new user to header
        const aesKeyBuffer = Buffer.from(aesKeyHex, 'hex');
        const updatedHeader = broadcastService.addUserToHeader(
            dataRecord.broadcastHeader || {},
            newUserId,
            newUserPublicKey,
            aesKeyBuffer
        );

        // Step 3: Write updated header back to blockchain
        const result = await contract.submitTransaction(
            'DataStorage:updateBroadcastHeader',
            dataId,
            JSON.stringify(updatedHeader),
            `add:${newUserId}`
        );

        return JSON.parse(result.toString());
    } finally {
        gateway.disconnect();
    }
}

// ─────────────────────────────────────────────────────────────
// getLogs — get full immutable access audit trail
// ─────────────────────────────────────────────────────────────
async function getLogs() {
    const { contract, gateway } = await getContract();
    try {
        const result = await contract.evaluateTransaction(
            'DataAccess:getLogs'
        );
        return JSON.parse(result.toString());
    } finally {
        gateway.disconnect();
    }
}

module.exports = {
    registerUser,
    assignLevel,
    storeHash,
    requestAccess,
    revokeAccess,         // NEW
    addAuthorizedUser,    // NEW
    getLogs
};